# Generated by Django 3.2.25 on 2025-03-18 21:53



from django.db import models

class User(models.Model):
    name = models.CharField(max_length=16, unique=True)
    password = models.CharField(max_length=16)

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=16, unique=True)
    password = models.CharField(max_length=16)

    def __str__(self):
        return self.name


class Course(models.Model):
    title = models.TextField()
    introduce = models.TextField()
    cover_url = models.TextField()
    video_url = models.TextField()
    category = models.CharField(max_length=16)
    chapter = models.CharField(max_length=16)

    def __str__(self):
        return self.title


class Comment(models.Model):
    c_content = models.TextField()
    c_username = models.CharField(max_length=16)
    c_course = models.ForeignKey(Course, on_delete=models.CASCADE)
    c_userputong = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.c_content


class CommentSecond(models.Model):
    cs_content = models.TextField()
    cs_username = models.CharField(max_length=16)
    cs_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    cs_teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.cs_content


class Topic(models.Model):
    problem = models.TextField()
    answer1 = models.TextField()
    answer2 = models.TextField()
    answer3 = models.TextField()
    answer4 = models.TextField()
    answer = models.CharField(max_length=16)
    content = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return self.problem
